import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from '../Providers/UserContext';
import { ToastProvider } from "@/Providers/ToastContext";
import ReactQueryProvider from "@/Providers/ReactQueryProvider";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <UserProvider>
                    <ToastProvider>
                        <ReactQueryProvider>{children}</ReactQueryProvider>
                    </ToastProvider>
                </UserProvider>
            </body>
        </html>
    );
}
